version: "3.9"

services:
  db:
    image: postgres:16
    container_name: participants_db
    restart: always
    environment:
      POSTGRES_DB: participants_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: participants_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:admin@db:5432/participants_db
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app

volumes:
  postgres_data: